#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRoar_Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DatabaseName")]
	public partial class ROARFormEntryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDVHAnalysis_DataEnterInstance(DVHAnalysis_DataEnterInstance instance);
    partial void UpdateDVHAnalysis_DataEnterInstance(DVHAnalysis_DataEnterInstance instance);
    partial void DeleteDVHAnalysis_DataEnterInstance(DVHAnalysis_DataEnterInstance instance);
    partial void InsertDVHAnalysis_PlanSum(DVHAnalysis_PlanSum instance);
    partial void UpdateDVHAnalysis_PlanSum(DVHAnalysis_PlanSum instance);
    partial void DeleteDVHAnalysis_PlanSum(DVHAnalysis_PlanSum instance);
    partial void InsertDVHAnalysis_PlanSetup(DVHAnalysis_PlanSetup instance);
    partial void UpdateDVHAnalysis_PlanSetup(DVHAnalysis_PlanSetup instance);
    partial void DeleteDVHAnalysis_PlanSetup(DVHAnalysis_PlanSetup instance);
    partial void InsertDVHAnalysis_Metric(DVHAnalysis_Metric instance);
    partial void UpdateDVHAnalysis_Metric(DVHAnalysis_Metric instance);
    partial void DeleteDVHAnalysis_Metric(DVHAnalysis_Metric instance);
    #endregion
		
		public ROARFormEntryDataContext() : 
				base(global::MRoar_Database.Properties.Settings.Default.ROARFormEntryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ROARFormEntryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROARFormEntryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROARFormEntryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROARFormEntryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DVHAnalysis_DataEnterInstance> DVHAnalysis_DataEnterInstances
		{
			get
			{
				return this.GetTable<DVHAnalysis_DataEnterInstance>();
			}
		}
		
		public System.Data.Linq.Table<DVHAnalysis_PlanSum> DVHAnalysis_PlanSums
		{
			get
			{
				return this.GetTable<DVHAnalysis_PlanSum>();
			}
		}
		
		public System.Data.Linq.Table<DVHAnalysis_PlanSetup> DVHAnalysis_PlanSetups
		{
			get
			{
				return this.GetTable<DVHAnalysis_PlanSetup>();
			}
		}
		
		public System.Data.Linq.Table<DVHAnalysis_Metric> DVHAnalysis_Metrics
		{
			get
			{
				return this.GetTable<DVHAnalysis_Metric>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DVHAnalysis_DataEnterInstance")]
	public partial class DVHAnalysis_DataEnterInstance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Instance_ID;
		
		private string _MRN;
		
		private System.Nullable<bool> _IsReIrradiationEvaluation;
		
		private System.DateTime _db_entry_time;
		
		private string _db_entry_userid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInstance_IDChanging(int value);
    partial void OnInstance_IDChanged();
    partial void OnMRNChanging(string value);
    partial void OnMRNChanged();
    partial void OnIsReIrradiationEvaluationChanging(System.Nullable<bool> value);
    partial void OnIsReIrradiationEvaluationChanged();
    partial void Ondb_entry_timeChanging(System.DateTime value);
    partial void Ondb_entry_timeChanged();
    partial void Ondb_entry_useridChanging(string value);
    partial void Ondb_entry_useridChanged();
    #endregion
		
		public DVHAnalysis_DataEnterInstance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instance_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Instance_ID
		{
			get
			{
				return this._Instance_ID;
			}
			set
			{
				if ((this._Instance_ID != value))
				{
					this.OnInstance_IDChanging(value);
					this.SendPropertyChanging();
					this._Instance_ID = value;
					this.SendPropertyChanged("Instance_ID");
					this.OnInstance_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MRN
		{
			get
			{
				return this._MRN;
			}
			set
			{
				if ((this._MRN != value))
				{
					this.OnMRNChanging(value);
					this.SendPropertyChanging();
					this._MRN = value;
					this.SendPropertyChanged("MRN");
					this.OnMRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReIrradiationEvaluation", DbType="Bit")]
		public System.Nullable<bool> IsReIrradiationEvaluation
		{
			get
			{
				return this._IsReIrradiationEvaluation;
			}
			set
			{
				if ((this._IsReIrradiationEvaluation != value))
				{
					this.OnIsReIrradiationEvaluationChanging(value);
					this.SendPropertyChanging();
					this._IsReIrradiationEvaluation = value;
					this.SendPropertyChanged("IsReIrradiationEvaluation");
					this.OnIsReIrradiationEvaluationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_time", DbType="DateTime NOT NULL")]
		public System.DateTime db_entry_time
		{
			get
			{
				return this._db_entry_time;
			}
			set
			{
				if ((this._db_entry_time != value))
				{
					this.Ondb_entry_timeChanging(value);
					this.SendPropertyChanging();
					this._db_entry_time = value;
					this.SendPropertyChanged("db_entry_time");
					this.Ondb_entry_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string db_entry_userid
		{
			get
			{
				return this._db_entry_userid;
			}
			set
			{
				if ((this._db_entry_userid != value))
				{
					this.Ondb_entry_useridChanging(value);
					this.SendPropertyChanging();
					this._db_entry_userid = value;
					this.SendPropertyChanged("db_entry_userid");
					this.Ondb_entry_useridChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DVHAnalysis_PlanSum")]
	public partial class DVHAnalysis_PlanSum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PlanSum_ID;
		
		private int _Instance_ID;
		
		private string _PlanSumID;
		
		private string _CompomentPlanSetupIDs;
		
		private System.Nullable<int> _ARIA_PlanSumSer;
		
		private string _MRN;
		
		private int _ARIA_PatientSer;
		
		private int _ARIA_CourseSer;
		
		private string _CourseID;
		
		private System.Nullable<System.DateTime> _CreationDateTime;
		
		private System.DateTime _db_entry_time;
		
		private string _db_entry_userid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlanSum_IDChanging(int value);
    partial void OnPlanSum_IDChanged();
    partial void OnInstance_IDChanging(int value);
    partial void OnInstance_IDChanged();
    partial void OnPlanSumIDChanging(string value);
    partial void OnPlanSumIDChanged();
    partial void OnCompomentPlanSetupIDsChanging(string value);
    partial void OnCompomentPlanSetupIDsChanged();
    partial void OnARIA_PlanSumSerChanging(System.Nullable<int> value);
    partial void OnARIA_PlanSumSerChanged();
    partial void OnMRNChanging(string value);
    partial void OnMRNChanged();
    partial void OnARIA_PatientSerChanging(int value);
    partial void OnARIA_PatientSerChanged();
    partial void OnARIA_CourseSerChanging(int value);
    partial void OnARIA_CourseSerChanged();
    partial void OnCourseIDChanging(string value);
    partial void OnCourseIDChanged();
    partial void OnCreationDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationDateTimeChanged();
    partial void Ondb_entry_timeChanging(System.DateTime value);
    partial void Ondb_entry_timeChanged();
    partial void Ondb_entry_useridChanging(string value);
    partial void Ondb_entry_useridChanged();
    #endregion
		
		public DVHAnalysis_PlanSum()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanSum_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PlanSum_ID
		{
			get
			{
				return this._PlanSum_ID;
			}
			set
			{
				if ((this._PlanSum_ID != value))
				{
					this.OnPlanSum_IDChanging(value);
					this.SendPropertyChanging();
					this._PlanSum_ID = value;
					this.SendPropertyChanged("PlanSum_ID");
					this.OnPlanSum_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instance_ID", DbType="Int NOT NULL")]
		public int Instance_ID
		{
			get
			{
				return this._Instance_ID;
			}
			set
			{
				if ((this._Instance_ID != value))
				{
					this.OnInstance_IDChanging(value);
					this.SendPropertyChanging();
					this._Instance_ID = value;
					this.SendPropertyChanged("Instance_ID");
					this.OnInstance_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanSumID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PlanSumID
		{
			get
			{
				return this._PlanSumID;
			}
			set
			{
				if ((this._PlanSumID != value))
				{
					this.OnPlanSumIDChanging(value);
					this.SendPropertyChanging();
					this._PlanSumID = value;
					this.SendPropertyChanged("PlanSumID");
					this.OnPlanSumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompomentPlanSetupIDs", DbType="NVarChar(250)")]
		public string CompomentPlanSetupIDs
		{
			get
			{
				return this._CompomentPlanSetupIDs;
			}
			set
			{
				if ((this._CompomentPlanSetupIDs != value))
				{
					this.OnCompomentPlanSetupIDsChanging(value);
					this.SendPropertyChanging();
					this._CompomentPlanSetupIDs = value;
					this.SendPropertyChanged("CompomentPlanSetupIDs");
					this.OnCompomentPlanSetupIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARIA_PlanSumSer", DbType="Int")]
		public System.Nullable<int> ARIA_PlanSumSer
		{
			get
			{
				return this._ARIA_PlanSumSer;
			}
			set
			{
				if ((this._ARIA_PlanSumSer != value))
				{
					this.OnARIA_PlanSumSerChanging(value);
					this.SendPropertyChanging();
					this._ARIA_PlanSumSer = value;
					this.SendPropertyChanged("ARIA_PlanSumSer");
					this.OnARIA_PlanSumSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MRN
		{
			get
			{
				return this._MRN;
			}
			set
			{
				if ((this._MRN != value))
				{
					this.OnMRNChanging(value);
					this.SendPropertyChanging();
					this._MRN = value;
					this.SendPropertyChanged("MRN");
					this.OnMRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARIA_PatientSer", DbType="Int NOT NULL")]
		public int ARIA_PatientSer
		{
			get
			{
				return this._ARIA_PatientSer;
			}
			set
			{
				if ((this._ARIA_PatientSer != value))
				{
					this.OnARIA_PatientSerChanging(value);
					this.SendPropertyChanging();
					this._ARIA_PatientSer = value;
					this.SendPropertyChanged("ARIA_PatientSer");
					this.OnARIA_PatientSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARIA_CourseSer", DbType="Int NOT NULL")]
		public int ARIA_CourseSer
		{
			get
			{
				return this._ARIA_CourseSer;
			}
			set
			{
				if ((this._ARIA_CourseSer != value))
				{
					this.OnARIA_CourseSerChanging(value);
					this.SendPropertyChanging();
					this._ARIA_CourseSer = value;
					this.SendPropertyChanged("ARIA_CourseSer");
					this.OnARIA_CourseSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this.OnCourseIDChanging(value);
					this.SendPropertyChanging();
					this._CourseID = value;
					this.SendPropertyChanged("CourseID");
					this.OnCourseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationDateTime
		{
			get
			{
				return this._CreationDateTime;
			}
			set
			{
				if ((this._CreationDateTime != value))
				{
					this.OnCreationDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreationDateTime = value;
					this.SendPropertyChanged("CreationDateTime");
					this.OnCreationDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_time", DbType="DateTime NOT NULL")]
		public System.DateTime db_entry_time
		{
			get
			{
				return this._db_entry_time;
			}
			set
			{
				if ((this._db_entry_time != value))
				{
					this.Ondb_entry_timeChanging(value);
					this.SendPropertyChanging();
					this._db_entry_time = value;
					this.SendPropertyChanged("db_entry_time");
					this.Ondb_entry_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string db_entry_userid
		{
			get
			{
				return this._db_entry_userid;
			}
			set
			{
				if ((this._db_entry_userid != value))
				{
					this.Ondb_entry_useridChanging(value);
					this.SendPropertyChanging();
					this._db_entry_userid = value;
					this.SendPropertyChanged("db_entry_userid");
					this.Ondb_entry_useridChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DVHAnalysis_PlanSetup")]
	public partial class DVHAnalysis_PlanSetup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PlanSetup_ID;
		
		private int _Instance_ID;
		
		private string _PlanSetupID;
		
		private string _MRN;
		
		private int _ARIA_PatientSer;
		
		private int _ARIA_CourseSer;
		
		private string _CourseID;
		
		private System.Nullable<int> _ARIA_PlanSetupSer;
		
		private System.Nullable<int> _PlanSum_ID;
		
		private string _PlanSumID;
		
		private double _Component_Weight;
		
		private System.Nullable<int> _Component_NFractionsPlanned;
		
		private System.Nullable<int> _Component_NFractionsDelivered;
		
		private System.Nullable<bool> _IsVolumetricDoseComponent;
		
		private System.Nullable<bool> _IsPaperChartBasedComponent;
		
		private System.Nullable<System.DateTime> _CreationDateTime;
		
		private System.DateTime _db_entry_time;
		
		private string _db_entry_userid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlanSetup_IDChanging(int value);
    partial void OnPlanSetup_IDChanged();
    partial void OnInstance_IDChanging(int value);
    partial void OnInstance_IDChanged();
    partial void OnPlanSetupIDChanging(string value);
    partial void OnPlanSetupIDChanged();
    partial void OnMRNChanging(string value);
    partial void OnMRNChanged();
    partial void OnARIA_PatientSerChanging(int value);
    partial void OnARIA_PatientSerChanged();
    partial void OnARIA_CourseSerChanging(int value);
    partial void OnARIA_CourseSerChanged();
    partial void OnCourseIDChanging(string value);
    partial void OnCourseIDChanged();
    partial void OnARIA_PlanSetupSerChanging(System.Nullable<int> value);
    partial void OnARIA_PlanSetupSerChanged();
    partial void OnPlanSum_IDChanging(System.Nullable<int> value);
    partial void OnPlanSum_IDChanged();
    partial void OnPlanSumIDChanging(string value);
    partial void OnPlanSumIDChanged();
    partial void OnComponent_WeightChanging(double value);
    partial void OnComponent_WeightChanged();
    partial void OnComponent_NFractionsPlannedChanging(System.Nullable<int> value);
    partial void OnComponent_NFractionsPlannedChanged();
    partial void OnComponent_NFractionsDeliveredChanging(System.Nullable<int> value);
    partial void OnComponent_NFractionsDeliveredChanged();
    partial void OnIsVolumetricDoseComponentChanging(System.Nullable<bool> value);
    partial void OnIsVolumetricDoseComponentChanged();
    partial void OnIsPaperChartBasedComponentChanging(System.Nullable<bool> value);
    partial void OnIsPaperChartBasedComponentChanged();
    partial void OnCreationDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationDateTimeChanged();
    partial void Ondb_entry_timeChanging(System.DateTime value);
    partial void Ondb_entry_timeChanged();
    partial void Ondb_entry_useridChanging(string value);
    partial void Ondb_entry_useridChanged();
    #endregion
		
		public DVHAnalysis_PlanSetup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanSetup_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PlanSetup_ID
		{
			get
			{
				return this._PlanSetup_ID;
			}
			set
			{
				if ((this._PlanSetup_ID != value))
				{
					this.OnPlanSetup_IDChanging(value);
					this.SendPropertyChanging();
					this._PlanSetup_ID = value;
					this.SendPropertyChanged("PlanSetup_ID");
					this.OnPlanSetup_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instance_ID", DbType="Int NOT NULL")]
		public int Instance_ID
		{
			get
			{
				return this._Instance_ID;
			}
			set
			{
				if ((this._Instance_ID != value))
				{
					this.OnInstance_IDChanging(value);
					this.SendPropertyChanging();
					this._Instance_ID = value;
					this.SendPropertyChanged("Instance_ID");
					this.OnInstance_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanSetupID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PlanSetupID
		{
			get
			{
				return this._PlanSetupID;
			}
			set
			{
				if ((this._PlanSetupID != value))
				{
					this.OnPlanSetupIDChanging(value);
					this.SendPropertyChanging();
					this._PlanSetupID = value;
					this.SendPropertyChanged("PlanSetupID");
					this.OnPlanSetupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MRN
		{
			get
			{
				return this._MRN;
			}
			set
			{
				if ((this._MRN != value))
				{
					this.OnMRNChanging(value);
					this.SendPropertyChanging();
					this._MRN = value;
					this.SendPropertyChanged("MRN");
					this.OnMRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARIA_PatientSer", DbType="Int NOT NULL")]
		public int ARIA_PatientSer
		{
			get
			{
				return this._ARIA_PatientSer;
			}
			set
			{
				if ((this._ARIA_PatientSer != value))
				{
					this.OnARIA_PatientSerChanging(value);
					this.SendPropertyChanging();
					this._ARIA_PatientSer = value;
					this.SendPropertyChanged("ARIA_PatientSer");
					this.OnARIA_PatientSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARIA_CourseSer", DbType="Int NOT NULL")]
		public int ARIA_CourseSer
		{
			get
			{
				return this._ARIA_CourseSer;
			}
			set
			{
				if ((this._ARIA_CourseSer != value))
				{
					this.OnARIA_CourseSerChanging(value);
					this.SendPropertyChanging();
					this._ARIA_CourseSer = value;
					this.SendPropertyChanged("ARIA_CourseSer");
					this.OnARIA_CourseSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this.OnCourseIDChanging(value);
					this.SendPropertyChanging();
					this._CourseID = value;
					this.SendPropertyChanged("CourseID");
					this.OnCourseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARIA_PlanSetupSer", DbType="Int")]
		public System.Nullable<int> ARIA_PlanSetupSer
		{
			get
			{
				return this._ARIA_PlanSetupSer;
			}
			set
			{
				if ((this._ARIA_PlanSetupSer != value))
				{
					this.OnARIA_PlanSetupSerChanging(value);
					this.SendPropertyChanging();
					this._ARIA_PlanSetupSer = value;
					this.SendPropertyChanged("ARIA_PlanSetupSer");
					this.OnARIA_PlanSetupSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanSum_ID", DbType="Int")]
		public System.Nullable<int> PlanSum_ID
		{
			get
			{
				return this._PlanSum_ID;
			}
			set
			{
				if ((this._PlanSum_ID != value))
				{
					this.OnPlanSum_IDChanging(value);
					this.SendPropertyChanging();
					this._PlanSum_ID = value;
					this.SendPropertyChanged("PlanSum_ID");
					this.OnPlanSum_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanSumID", DbType="NVarChar(50)")]
		public string PlanSumID
		{
			get
			{
				return this._PlanSumID;
			}
			set
			{
				if ((this._PlanSumID != value))
				{
					this.OnPlanSumIDChanging(value);
					this.SendPropertyChanging();
					this._PlanSumID = value;
					this.SendPropertyChanged("PlanSumID");
					this.OnPlanSumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Component_Weight", DbType="Float NOT NULL")]
		public double Component_Weight
		{
			get
			{
				return this._Component_Weight;
			}
			set
			{
				if ((this._Component_Weight != value))
				{
					this.OnComponent_WeightChanging(value);
					this.SendPropertyChanging();
					this._Component_Weight = value;
					this.SendPropertyChanged("Component_Weight");
					this.OnComponent_WeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Component_NFractionsPlanned", DbType="Int")]
		public System.Nullable<int> Component_NFractionsPlanned
		{
			get
			{
				return this._Component_NFractionsPlanned;
			}
			set
			{
				if ((this._Component_NFractionsPlanned != value))
				{
					this.OnComponent_NFractionsPlannedChanging(value);
					this.SendPropertyChanging();
					this._Component_NFractionsPlanned = value;
					this.SendPropertyChanged("Component_NFractionsPlanned");
					this.OnComponent_NFractionsPlannedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Component_NFractionsDelivered", DbType="Int")]
		public System.Nullable<int> Component_NFractionsDelivered
		{
			get
			{
				return this._Component_NFractionsDelivered;
			}
			set
			{
				if ((this._Component_NFractionsDelivered != value))
				{
					this.OnComponent_NFractionsDeliveredChanging(value);
					this.SendPropertyChanging();
					this._Component_NFractionsDelivered = value;
					this.SendPropertyChanged("Component_NFractionsDelivered");
					this.OnComponent_NFractionsDeliveredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVolumetricDoseComponent", DbType="Bit")]
		public System.Nullable<bool> IsVolumetricDoseComponent
		{
			get
			{
				return this._IsVolumetricDoseComponent;
			}
			set
			{
				if ((this._IsVolumetricDoseComponent != value))
				{
					this.OnIsVolumetricDoseComponentChanging(value);
					this.SendPropertyChanging();
					this._IsVolumetricDoseComponent = value;
					this.SendPropertyChanged("IsVolumetricDoseComponent");
					this.OnIsVolumetricDoseComponentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPaperChartBasedComponent", DbType="Bit")]
		public System.Nullable<bool> IsPaperChartBasedComponent
		{
			get
			{
				return this._IsPaperChartBasedComponent;
			}
			set
			{
				if ((this._IsPaperChartBasedComponent != value))
				{
					this.OnIsPaperChartBasedComponentChanging(value);
					this.SendPropertyChanging();
					this._IsPaperChartBasedComponent = value;
					this.SendPropertyChanged("IsPaperChartBasedComponent");
					this.OnIsPaperChartBasedComponentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationDateTime
		{
			get
			{
				return this._CreationDateTime;
			}
			set
			{
				if ((this._CreationDateTime != value))
				{
					this.OnCreationDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreationDateTime = value;
					this.SendPropertyChanged("CreationDateTime");
					this.OnCreationDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_time", DbType="DateTime NOT NULL")]
		public System.DateTime db_entry_time
		{
			get
			{
				return this._db_entry_time;
			}
			set
			{
				if ((this._db_entry_time != value))
				{
					this.Ondb_entry_timeChanging(value);
					this.SendPropertyChanging();
					this._db_entry_time = value;
					this.SendPropertyChanged("db_entry_time");
					this.Ondb_entry_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string db_entry_userid
		{
			get
			{
				return this._db_entry_userid;
			}
			set
			{
				if ((this._db_entry_userid != value))
				{
					this.Ondb_entry_useridChanging(value);
					this.SendPropertyChanging();
					this._db_entry_userid = value;
					this.SendPropertyChanged("db_entry_userid");
					this.Ondb_entry_useridChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DVHAnalysis_Metric")]
	public partial class DVHAnalysis_Metric : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Metric_ID;
		
		private int _Instance_ID;
		
		private System.Nullable<int> _PlanSum_ID;
		
		private System.Nullable<int> _PlanSetup_ID;
		
		private string _StructureID;
		
		private string _DVHMetricName;
		
		private double _DVHMetricValue;
		
		private string _StructureSetID;
		
		private System.Nullable<bool> _IsReIrradiationEvaluation;
		
		private System.Nullable<bool> _IsVolumetricDVHDoseEstimate;
		
		private System.Nullable<bool> _IsPointDoseEstimate;
		
		private System.DateTime _db_entry_time;
		
		private string _db_entry_userid;
		
		private string _Comment;
		
		private string _db_entry_source;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMetric_IDChanging(int value);
    partial void OnMetric_IDChanged();
    partial void OnInstance_IDChanging(int value);
    partial void OnInstance_IDChanged();
    partial void OnPlanSum_IDChanging(System.Nullable<int> value);
    partial void OnPlanSum_IDChanged();
    partial void OnPlanSetup_IDChanging(System.Nullable<int> value);
    partial void OnPlanSetup_IDChanged();
    partial void OnStructureIDChanging(string value);
    partial void OnStructureIDChanged();
    partial void OnDVHMetricNameChanging(string value);
    partial void OnDVHMetricNameChanged();
    partial void OnDVHMetricValueChanging(double value);
    partial void OnDVHMetricValueChanged();
    partial void OnStructureSetIDChanging(string value);
    partial void OnStructureSetIDChanged();
    partial void OnIsReIrradiationEvaluationChanging(System.Nullable<bool> value);
    partial void OnIsReIrradiationEvaluationChanged();
    partial void OnIsVolumetricDVHDoseEstimateChanging(System.Nullable<bool> value);
    partial void OnIsVolumetricDVHDoseEstimateChanged();
    partial void OnIsPointDoseEstimateChanging(System.Nullable<bool> value);
    partial void OnIsPointDoseEstimateChanged();
    partial void Ondb_entry_timeChanging(System.DateTime value);
    partial void Ondb_entry_timeChanged();
    partial void Ondb_entry_useridChanging(string value);
    partial void Ondb_entry_useridChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void Ondb_entry_sourceChanging(string value);
    partial void Ondb_entry_sourceChanged();
    #endregion
		
		public DVHAnalysis_Metric()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metric_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Metric_ID
		{
			get
			{
				return this._Metric_ID;
			}
			set
			{
				if ((this._Metric_ID != value))
				{
					this.OnMetric_IDChanging(value);
					this.SendPropertyChanging();
					this._Metric_ID = value;
					this.SendPropertyChanged("Metric_ID");
					this.OnMetric_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instance_ID", DbType="Int NOT NULL")]
		public int Instance_ID
		{
			get
			{
				return this._Instance_ID;
			}
			set
			{
				if ((this._Instance_ID != value))
				{
					this.OnInstance_IDChanging(value);
					this.SendPropertyChanging();
					this._Instance_ID = value;
					this.SendPropertyChanged("Instance_ID");
					this.OnInstance_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanSum_ID", DbType="Int")]
		public System.Nullable<int> PlanSum_ID
		{
			get
			{
				return this._PlanSum_ID;
			}
			set
			{
				if ((this._PlanSum_ID != value))
				{
					this.OnPlanSum_IDChanging(value);
					this.SendPropertyChanging();
					this._PlanSum_ID = value;
					this.SendPropertyChanged("PlanSum_ID");
					this.OnPlanSum_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanSetup_ID", DbType="Int")]
		public System.Nullable<int> PlanSetup_ID
		{
			get
			{
				return this._PlanSetup_ID;
			}
			set
			{
				if ((this._PlanSetup_ID != value))
				{
					this.OnPlanSetup_IDChanging(value);
					this.SendPropertyChanging();
					this._PlanSetup_ID = value;
					this.SendPropertyChanged("PlanSetup_ID");
					this.OnPlanSetup_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StructureID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StructureID
		{
			get
			{
				return this._StructureID;
			}
			set
			{
				if ((this._StructureID != value))
				{
					this.OnStructureIDChanging(value);
					this.SendPropertyChanging();
					this._StructureID = value;
					this.SendPropertyChanged("StructureID");
					this.OnStructureIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVHMetricName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DVHMetricName
		{
			get
			{
				return this._DVHMetricName;
			}
			set
			{
				if ((this._DVHMetricName != value))
				{
					this.OnDVHMetricNameChanging(value);
					this.SendPropertyChanging();
					this._DVHMetricName = value;
					this.SendPropertyChanged("DVHMetricName");
					this.OnDVHMetricNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVHMetricValue", DbType="Float NOT NULL")]
		public double DVHMetricValue
		{
			get
			{
				return this._DVHMetricValue;
			}
			set
			{
				if ((this._DVHMetricValue != value))
				{
					this.OnDVHMetricValueChanging(value);
					this.SendPropertyChanging();
					this._DVHMetricValue = value;
					this.SendPropertyChanged("DVHMetricValue");
					this.OnDVHMetricValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StructureSetID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StructureSetID
		{
			get
			{
				return this._StructureSetID;
			}
			set
			{
				if ((this._StructureSetID != value))
				{
					this.OnStructureSetIDChanging(value);
					this.SendPropertyChanging();
					this._StructureSetID = value;
					this.SendPropertyChanged("StructureSetID");
					this.OnStructureSetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReIrradiationEvaluation", DbType="Bit")]
		public System.Nullable<bool> IsReIrradiationEvaluation
		{
			get
			{
				return this._IsReIrradiationEvaluation;
			}
			set
			{
				if ((this._IsReIrradiationEvaluation != value))
				{
					this.OnIsReIrradiationEvaluationChanging(value);
					this.SendPropertyChanging();
					this._IsReIrradiationEvaluation = value;
					this.SendPropertyChanged("IsReIrradiationEvaluation");
					this.OnIsReIrradiationEvaluationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVolumetricDVHDoseEstimate", DbType="Bit")]
		public System.Nullable<bool> IsVolumetricDVHDoseEstimate
		{
			get
			{
				return this._IsVolumetricDVHDoseEstimate;
			}
			set
			{
				if ((this._IsVolumetricDVHDoseEstimate != value))
				{
					this.OnIsVolumetricDVHDoseEstimateChanging(value);
					this.SendPropertyChanging();
					this._IsVolumetricDVHDoseEstimate = value;
					this.SendPropertyChanged("IsVolumetricDVHDoseEstimate");
					this.OnIsVolumetricDVHDoseEstimateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPointDoseEstimate", DbType="Bit")]
		public System.Nullable<bool> IsPointDoseEstimate
		{
			get
			{
				return this._IsPointDoseEstimate;
			}
			set
			{
				if ((this._IsPointDoseEstimate != value))
				{
					this.OnIsPointDoseEstimateChanging(value);
					this.SendPropertyChanging();
					this._IsPointDoseEstimate = value;
					this.SendPropertyChanged("IsPointDoseEstimate");
					this.OnIsPointDoseEstimateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_time", DbType="DateTime NOT NULL")]
		public System.DateTime db_entry_time
		{
			get
			{
				return this._db_entry_time;
			}
			set
			{
				if ((this._db_entry_time != value))
				{
					this.Ondb_entry_timeChanging(value);
					this.SendPropertyChanging();
					this._db_entry_time = value;
					this.SendPropertyChanged("db_entry_time");
					this.Ondb_entry_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string db_entry_userid
		{
			get
			{
				return this._db_entry_userid;
			}
			set
			{
				if ((this._db_entry_userid != value))
				{
					this.Ondb_entry_useridChanging(value);
					this.SendPropertyChanging();
					this._db_entry_userid = value;
					this.SendPropertyChanged("db_entry_userid");
					this.Ondb_entry_useridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(1024)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_entry_source", DbType="NVarChar(512)")]
		public string db_entry_source
		{
			get
			{
				return this._db_entry_source;
			}
			set
			{
				if ((this._db_entry_source != value))
				{
					this.Ondb_entry_sourceChanging(value);
					this.SendPropertyChanging();
					this._db_entry_source = value;
					this.SendPropertyChanged("db_entry_source");
					this.Ondb_entry_sourceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
