<?xml version="1.0" encoding="utf-8"?><Database Name="ROARFormEntry" Class="ROARFormEntryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ServerName;Initial Catalog=DatabaseName;Integrated Security=True" SettingsObjectName="MRoar_Database.Properties.Settings" SettingsPropertyName="ROARFormEntryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DVHAnalysis_DataEnterInstance" Member="DVHAnalysis_DataEnterInstances">
    <Type Name="DVHAnalysis_DataEnterInstance">
      <Column Name="Instance_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MRN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsReIrradiationEvaluation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="db_entry_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="db_entry_userid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DVHAnalysis_PlanSum" Member="DVHAnalysis_PlanSums">
    <Type Name="DVHAnalysis_PlanSum">
      <Column Name="PlanSum_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Instance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlanSumID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompomentPlanSetupIDs" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ARIA_PlanSumSer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MRN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ARIA_PatientSer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ARIA_CourseSer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreationDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="db_entry_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="db_entry_userid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DVHAnalysis_PlanSetup" Member="DVHAnalysis_PlanSetups">
    <Type Name="DVHAnalysis_PlanSetup">
      <Column Name="PlanSetup_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Instance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlanSetupID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MRN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ARIA_PatientSer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ARIA_CourseSer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ARIA_PlanSetupSer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlanSum_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlanSumID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Component_Weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Component_NFractionsPlanned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Component_NFractionsDelivered" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsVolumetricDoseComponent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPaperChartBasedComponent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreationDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="db_entry_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="db_entry_userid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DVHAnalysis_Metric" Member="DVHAnalysis_Metrics">
    <Type Name="DVHAnalysis_Metric">
      <Column Name="Metric_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Instance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlanSum_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlanSetup_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StructureID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DVHMetricName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DVHMetricValue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="StructureSetID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsReIrradiationEvaluation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsVolumetricDVHDoseEstimate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPointDoseEstimate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="db_entry_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="db_entry_userid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="db_entry_source" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
</Database>